# Generated by Django 4.1.7 on 2023-04-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0002_alter_apartamento_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='morador_principal',
        ),
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='app_meu_pacote.apartamento'),
        ),
    ]
