# Generated by Django 4.1.7 on 2023-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0003_remove_apartamento_morador_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data_hora_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
