# Generated by Django 4.1.7 on 2023-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0004_alter_encomenda_data_hora_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='idpacote',
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='morador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
