# Generated by Django 4.1.7 on 2023-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0005_remove_encomenda_idpacote_alter_apartamento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='codigo_retirada',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
