# Generated by Django 4.1.7 on 2023-05-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0006_encomenda_codigo_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='app_meu_pacote.condominio'),
            preserve_default=False,
        ),
    ]
