# Generated by Django 4.1.7 on 2023-05-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_meu_pacote', '0008_encomenda_funcionario_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='entregue',
        ),
    ]
