# Generated by Django 4.1.7 on 2023-05-18 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_meu_pacote', '0009_remove_encomenda_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
